### ISSUE TITLE
Do you use the PDR model

### ISSUE THREAD

**Issue by panlongming** [Navigine/Indoor-Positioning-And-Navigation-Algorithms#28]

**Comment by PavelTychinin** [comment]
Yes. You can find source code here https://github.com/Navigine/Indoor-Positioning-And-Navigation-Algorithms/tree/master/standalone_algorithms/pedometer

**Comment by panlongming** [comment]
Does the algorithm  only use the  acceleration data,not gyroscope data？

**Comment by fedormex** [comment]
> Does the algorithm only use the acceleration data,not gyroscope data？

Gyroscope and magnitometer data can be handled using complementary filter: https://github.com/Navigine/Indoor-Positioning-And-Navigation-Algorithms/tree/master/standalone_algorithms/complementary_filter

You can see the example of using it here: https://github.com/Navigine/Indoor-Positioning-And-Navigation-Algorithms/blob/master/standalone_algorithms/complementary_filter/examples/main.cpp#L157

**Comment by panlongming** [comment]
Do you mean to use complementary filtering to fuse gyroscope and magnetometer data sets to improve the accuracy of PDR?

**Comment by fedormex** [comment]
Not exactly, I would say: pedometer+ complementary filter forms the PDR algorithm. Pedometer itself allows to detect steps and their length while complementary filter allows to determine direction. So, joining these two components together you can get a PDR trajectory.

**Comment by panlongming** [comment]
OH，I know,you have build the compleat pdr algorithm,what you mean is i just only use the pedometer+ complementary file to perform the pdr alogrithm.Is this ?

**Comment by panlongming** [comment]
that have the complete pdr algorithm in the file

**Comment by fedormex** [comment]
> OH，I know,you have build the compleat pdr algorithm,what you mean is i just only use the pedometer+ complementary file to perform the pdr alogrithm.Is this ?

Yes. If you need to implement a PDR algorithm (building pedestrian trajectory based on sensors) you should use both pedometer and complementary fileter.

**Comment by panlongming** [comment]
Thank you，I get it

**Comment by panlongming** [comment]
I am an algorithm engineer for indoor positioning. Can I add your email address to contact you for further information?

**Comment by fedormex** [comment]
Yes, sure.

**Comment by panlongming** [comment]
Can you send a message to me from emai? my email is panlongming@meta-bounds.com

**Comment by panlongming** [comment]
How to contact you？

**Comment by panlongming** [comment]
How should I contact you?

**Comment by fedormex** [comment]
fedormex@gmail.com
